version: "3"
services:
  web:
    image: nginx:1.12-alpine
    volumes:
      - public_html:/usr/share/nginx/html
    restart: always
    ports: # host:container
      - "8194:80"
  weewx:
    environment:
      - CONF=default
    build: ./
    image: weewx:4.0.0b3
    volumes:
    # public_html - shared with web service - def is in volumes: below
      - public_html:/home/weewx/public_html
    # another option: local directory, so the db doesnt start from scratch
      - ./archive:/home/weewx/archive
    restart: always
volumes:
  public_html:
